para='''The apple doesn't fall. ...
All that glitters are not gold. ...
A picture is worth a thousand words. ...
Beggers can't be choosers. ...
A bird in the hand. ...
Better safe than sorry. ...
An apple a day keeps doctor away. ...
Blood is thicker than water. ...'''
lines=para.split("\n")
print("Number of lines :",len(lines))
c=0
for line in lines:
    if(line[0]=='B'):
        c+=1
print("Starts with B :",c)
   
